# Testing Notebook
This notebook will be used for carrying out test cases as well as explaining/logicing the steps of the 2 phase simplex method employed in this repo. \
An understanding of the phase 1 simplex method is required to understand the following (as explaining/deriving everything would take a very long time).

In [1]:
import random
import numpy as np

## Tableau Construction
Here we will justify and test how the tableau construction will work in our program.

Here our problems are solveable from the following form:\
$  \text{min }c\cdot x$ \
$  \text{s.t. } Ax = b$ \
$  x \geq 0$ 
\
\
Our auxllary problem (to solve problems with no apparent basis, i.e. no apparent identity basic matrix fromed in matrix A) is then: \
$  \text{min } e\cdot y$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$
\
\
Hence our problem for the auxillary problem can be proven to be the following: \
$\text{min } e\cdot(b-Ax)$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$ \
\
So our tableau becomes:
| $-e\cdot b$| $-eA$ | $0...0$ |
| :----------:| :-----:| :----: |
| $b$        |   $A$  | $I$ |

Notice the following facts:
1. Our tableau can be represented as a matrix of size $(m+1) \times (m+n+1)$
2. This tableau can be constructed numerically

We use numpy.linalg to compute matrix multiplication as prescribed above. \
Note that we only have a valid solution if the y variables are all 0, otherwise the original problem's constraints are violated.

### Tableau Construction for the 2 phase simplex method

### Tableau construction tests

In [2]:
from two_phase_simplex import TwoPhaseSimplex

# test the basic tableau construction of the auxillary problem
# simple 2x2 matrix case
A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
x.complete_phase_one()
print(x.get_tableau())

# non-square matrix
A = [[3,2,2],[4,5,4],[2,1,1],[0,1,1]]
b = [1,2,3,4]
c = [-1,-2,3]
y = TwoPhaseSimplex(A,b,c)
y.complete_phase_one()
print(y.get_tableau())

# check if these two outputs check out

[[ 0.  0.  0.  1.  1.]
 [ 2.  1.  0.  1.  0.]
 [ 1.  0.  1. -1.  1.]]
[[-6.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  3.50000000e+00  0.00000000e+00  1.00000000e+00
   2.50000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.00000000e+00  0.00000000e+00
  -2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.50000000e+00  5.00000000e-01  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 3.50000000e+00 -1.50000000e+00  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  5.55111512e-17  0.00000000e+00  1.00000000e+00]]


### Tableau feasibility tests

#### Feasiblity via violation of auxillary problems non-negativity constaint

In [3]:
# Simple problem (can be solved using normal gaussian elimination lol)

A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
if (x.solve_program()):
    print(x.get_solution())

# unbounded problem

A = [[3,4,5],[42,5,1],[2,5,4]]
b = [1,2,3]
c = [2,3,1]

y = TwoPhaseSimplex(A,b,c)
if y.solve_program():
    print(y.get_solution())

# higher dimension bounded problem

A = [[2,3,1,0],[3,1,0,-1]]
b = [6,3]
c = [-4,-5,0,0]

z = TwoPhaseSimplex(A,b,c)
if z.solve_program():
    print(z.get_solution())

{'x1': 2.0, 'x2': 1.0}
{'x1': -0.07874015748031496, 'x2': 1.204724409448819, 'x3': -0.7165354330708661}
{'x1': 3.0, 'x2': 0.0, 'x3': 0.0, 'x4': 6.0}


## Random Test Cases

In [4]:
# produce random test cases

test_cases : dict = {"A" : [], "b" : [], "c" : []}

cases : int = 100

for i in range(cases):
    m : int = random.randint(2, 100)
    n : int = random.randint(2, 100)
    test_cases["A"].append(np.random.rand(m,n))
    test_cases["b"].append(np.random.rand(m))
    test_cases["c"].append(np.random.rand(n))

for i in range(cases):
    x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
    if x.solve_program():
        print(x.get_solution())

{'x1': 0.3241220581890175, 'x2': -0.26502238977128684, 'x3': -0.530406607464407, 'x4': 0.5224382974073946, 'x5': 0.34647527270061496, 'x6': 0.2684157999533796, 'x7': -0.3359923113629443, 'x8': -0.521418086741099, 'x9': 0.07620798707736864, 'x10': 0.17853100732144023, 'x11': -0.32964001780592417, 'x12': 0.0, 'x13': 0.0, 'x14': 0.0, 'x15': 0.0, 'x16': 0.0, 'x17': -0.3283504544585708, 'x18': 0.0, 'x19': 0.0, 'x20': 0.28719091186770285, 'x21': 0.0, 'x22': 0.0, 'x23': 0.0, 'x24': 0.0, 'x25': 0.0, 'x26': 0.0, 'x27': 0.0, 'x28': 0.0, 'x29': 0.0, 'x30': 0.0, 'x31': 0.0, 'x32': 0.0, 'x33': -0.06370948174630248, 'x34': 0.0, 'x35': 0.4679403355007012, 'x36': 0.0, 'x37': 0.956167327082943, 'x38': 0.0, 'x39': 0.0, 'x40': 0.0}
{'x1': -0.24821352425304488, 'x2': -0.09829497883101815, 'x3': 0.6838825117931651, 'x4': 1.8366630354914681, 'x5': -0.8327258706751295, 'x6': 0.6599886851891368, 'x7': -0.295271213739302, 'x8': -0.22719801605636736, 'x9': -0.2985661452530922, 'x10': -0.7287764876030133, 'x11':

### Observations from the random tests
A very large amount of 'random' (generated by numpy) problems are infeasible or unbounded, hence do not have an optimal solution. In the next couple cells I will try to present these facts using graphs.

In [5]:
def get_random_results(cases : np.array) -> np.array:
    """
    Runs the two phase simplex solver using random shape of matrices and entries.
    Returns a list of n results.
    """
    results = np.zeros(len(cases))
    for j,case in enumerate(cases):
        for i in range(int(case)):
            m : int = random.randint(9, 300)
            n : int = m - 5
            test_cases["A"].append(np.random.rand(m,n))
            test_cases["b"].append(np.random.rand(m))
            test_cases["c"].append(np.random.rand(n))


        for i in range(int(case)):
            x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
            if x.solve_program():
                results[j] += 1

    return results

In [6]:
# import matplotlib.pyplot as plt

# x = np.logspace(1, 3, base=10)
# print(x)
# y = np.zeros(len(x))

# y = get_random_results(x)

# print(y)

## Input sanitisation tests

In [7]:
# should raise exception with a message

A = [[3],[2],[4]] # A is a 3x1 matrix
b = [1,2] # b has size 2
c = [1] # c has size 1

x = TwoPhaseSimplex(A, b, c)

Exception: Invalid linear programming problem described: Vector b does not have the same length as matrix A has rows

In [ ]:
# should raise exception with a message

A = [[3,-1],[2,5]] # A is a 3x2 matrix
b = [1,2,5] # b has size 3
c = [1] # c has size 1

x = TwoPhaseSimplex(A, b, c)

Exception: Invalid linear programming problem described: Vector b does not have the same length as matrix A has rows

In [ ]:
# should work with no exception

A = [[3,-1],[2,5]] # A is a 3x2 matrix
b = [1,2] # b has size 2
c = [1,2] # c has size 2

x = TwoPhaseSimplex(A, b, c)

## More test cases for solutions

In [ ]:
A = [[2,0,3],[3,2,-1]]
b = [1,5]
c = [1,-2,0]

# this problem should read off the solution (x1,x2,x3) = (0,1/3,8/3)

x = TwoPhaseSimplex(A,b,c)
if x.solve_program():
    print(x.get_solution())

e = [[1,2,3],[-1,2,6],[0,-3,-9]]
f = [3,2,-5]
g = [1,1,1]

y = TwoPhaseSimplex(e,f,g)

if y.solve_program():
    print(y.get_solution())

assert x.get_solution(), {'x1':0,'x2':8/3,'x3':1/3}
assert y.get_solution(), {'x1':4/3,'x2':0,'x3':5/9}

{'x1': 0.0, 'x2': 2.6666666666666665, 'x3': 0.3333333333333333}
{'x1': 1.3333333333333335, 'x2': 0.0, 'x3': 0.5555555555555556}
