# Testing Notebook
This notebook will be used for carrying out test cases as well as explaining/logicing the steps of the 2 phase simplex method employed in this repo. \
An understanding of the phase 1 simplex method is required to understand the following (as explaining/deriving everything would take a very long time).

In [1]:
import random
import numpy as np

## Tableau Construction
Here we will justify and test how the tableau construction will work in our program.

Here our problems are solveable from the following form:\
$  \text{min }c\cdot x$ \
$  \text{s.t. } Ax = b$ \
$  x \geq 0$ 
\
\
Our auxllary problem (to solve problems with no apparent basis, i.e. no apparent identity basic matrix fromed in matrix A) is then: \
$  \text{min } e\cdot y$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$
\
\
Hence our problem for the auxillary problem can be proven to be the following: \
$\text{min } e\cdot(b-Ax)$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$ \
\
So our tableau becomes:
| $-e\cdot b$| $-eA$ | $0...0$ |
| :----------:| :-----:| :----: |
| $b$        |   $A$  | $I$ |

Notice the following facts:
1. Our tableau can be represented as a matrix of size $(m+1) \times (m+n+1)$
2. This tableau can be constructed numerically

We use numpy.linalg to compute matrix multiplication as prescribed above. \
Note that we only have a valid solution if the y variables are all 0, otherwise the original problem's constraints are violated.

### Tableau Construction for the 2 phase simplex method

### Tableau construction tests

In [2]:
from two_phase_simplex import TwoPhaseSimplex

# test the basic tableau construction of the auxillary problem
# simple 2x2 matrix case
A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
x.solve_phase_one()
print(x.get_tableau())

# non-square matrix
A = [[3,2,2],[4,5,4],[2,1,1],[0,1,1]]
b = [1,2,3,4]
c = [-1,-2,3]
y = TwoPhaseSimplex(A,b,c)
y.solve_phase_one()
print(y.get_tableau())

# check if these two outputs check out

[[ 0.  0.  0.  1.  1.]
 [ 2.  1.  0.  1.  0.]
 [ 1.  0.  1. -1.  1.]]
[[-6.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  3.50000000e+00  0.00000000e+00  1.00000000e+00
   2.50000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.00000000e+00  0.00000000e+00
  -2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.50000000e+00  5.00000000e-01  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 3.50000000e+00 -1.50000000e+00  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  5.55111512e-17  0.00000000e+00  1.00000000e+00]]


### Tableau feasibility tests

#### Feasiblity via violation of auxillary problems non-negativity constaint

In [3]:
# Simple problem (can be solved using normal gaussian elimination lol)

A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
if (x.solve_program()):
    print(x.get_solution())

# unbounded problem

A = [[3,4,5],[42,5,1],[2,5,4]]
b = [1,2,3]
c = [2,3,1]

y = TwoPhaseSimplex(A,b,c)
if y.solve_program():
    print(y.get_solution())

# higher dimension bounded problem

A = [[2,3,1,0],[3,1,0,-1]]
b = [6,3]
c = [-4,-5,0,0]

z = TwoPhaseSimplex(A,b,c)
if z.solve_program():
    print(z.get_solution())

{'x1': 2.0, 'x2': 1.0}
{'x1': -0.07874015748031496, 'x2': 1.204724409448819, 'x3': -0.7165354330708661}
{'x1': 3.0, 'x2': 0.0, 'x3': 0.0, 'x4': 6.0}


## Random Test Cases

In [4]:
# produce random test cases

test_cases : dict = {"A" : [], "b" : [], "c" : []}

cases : int = 100

for i in range(cases):
    m : int = random.randint(2, 100)
    n : int = random.randint(2, 100)
    test_cases["A"].append(np.random.rand(m,n))
    test_cases["b"].append(np.random.rand(m))
    test_cases["c"].append(np.random.rand(n))

for i in range(cases):
    x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
    if x.solve_program():
        print(x.get_solution())

{'x1': -85.70956256945315, 'x2': -248.06355647491222, 'x3': 26.027285603049826, 'x4': 89.30059994356944, 'x5': -12.619834662866054, 'x6': -25.667361360726805, 'x7': 68.58617485813268, 'x8': -77.609807544602, 'x9': -103.57695151683755, 'x10': -17.316680570360234, 'x11': -321.5393380646464, 'x12': -54.74265607997732, 'x13': -194.72430292996137, 'x14': 93.92525207870573, 'x15': -22.357775528739467, 'x16': -212.21244537110346, 'x17': -4.758150510261327, 'x18': -86.364203361403, 'x19': 223.02096070579532, 'x20': -180.5245993810052, 'x21': 297.1121324628207, 'x22': 22.934457651922575, 'x23': 48.74995010912538, 'x24': 204.48572219330646, 'x25': -151.8780095894965, 'x26': -54.05742607272212, 'x27': 11.605149519160504, 'x28': -247.0298358607952, 'x29': 70.77561387830298, 'x30': 206.11787078714212, 'x31': 132.16346185685353, 'x32': -112.15118417901321, 'x33': 112.34377508175412, 'x34': -87.43200898540269, 'x35': -24.76718491562351, 'x36': -99.2186606943394, 'x37': 227.9089455876898, 'x38': -334.

### Observations from the random tests
A very large amount of 'random' (generated by numpy) problems are infeasible or unbounded, hence do not have an optimal solution. In the next couple cells I will try to present these facts using graphs.

In [5]:
def get_random_results(cases : np.array) -> np.array:
    """
    Runs the two phase simplex solver using random shape of matrices and entries.
    Returns a list of n results.
    """
    results = np.zeros(len(cases))
    for j,case in enumerate(cases):
        for i in range(int(case)):
            m : int = random.randint(9, 300)
            n : int = m - 5
            test_cases["A"].append(np.random.rand(m,n))
            test_cases["b"].append(np.random.rand(m))
            test_cases["c"].append(np.random.rand(n))


        for i in range(int(case)):
            x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
            if x.solve_program():
                results[j] += 1

    return results

In [6]:
# import matplotlib.pyplot as plt

# x = np.logspace(1, 3, base=10)
# print(x)
# y = np.zeros(len(x))

# y = get_random_results(x)

# print(y)

## Input sanitisation tests

In [7]:
# should raise exception with a message

A = [[3],[2],[4]] # A is a 3x1 matrix
b = [1,2] # b has size 2
c = [1] # c has size 1

x = TwoPhaseSimplex(A, b, c)

Exception: Invalid linear programming problem described: Vector b does not have the same length as matrix A has rows

In [8]:
# should raise exception with a message

A = [[3,-1],[2,5]] # A is a 3x2 matrix
b = [1,2,5] # b has size 3
c = [1] # c has size 1

x = TwoPhaseSimplex(A, b, c)

Exception: Invalid linear programming problem described: Vector b does not have the same length as matrix A has rows

In [9]:
# should work with no exception

A = [[3,-1],[2,5]] # A is a 3x2 matrix
b = [1,2] # b has size 2
c = [1,2] # c has size 2

x = TwoPhaseSimplex(A, b, c)

## More test cases for solutions

In [11]:
A = [[2,0,3],[3,2,-1]]
b = [1,5]
c = [1,-2,0]

# this problem should read off the solution (x1,x2,x3) = (0,1/3,8/3)

x = TwoPhaseSimplex(A,b,c)
if x.solve_program():
    print(x.get_solution())

e = [[1,2,3],[-1,2,6],[0,-3,-9]]
f = [3,2,-5]
g = [1,1,1]

y = TwoPhaseSimplex(e,f,g)

if y.solve_program():
    print(y.get_solution())

assert x.get_solution(), {'x1':0,'x2':8/3,'x3':1/3}
assert y.get_solution(), {'x1':4/3,'x2':0,'x3':5/9}

{'x1': 0.0, 'x2': 2.6666666666666665, 'x3': 0.3333333333333333}
{'x1': 1.3333333333333335, 'x2': 0.0, 'x3': 0.5555555555555556}
