# Testing Notebook
This notebook will be used for carrying out test cases as well as explaining/logicing the steps of the 2 phase simplex method employed in this repo. \
An understanding of the phase 1 simplex method is required to understand the following (as explaining/deriving everything would take a very long time).

In [11]:
import random
import numpy as np

## Tableau Construction
Here we will justify and test how the tableau construction will work in our program.

### Tableau Construction for the 2 phase simplex method

Here our problems are solveable from the following form:\
$  \text{min }c\cdot x$ \
$  \text{s.t. } Ax = b$ \
$  x \geq 0$ 
\
\
Our auxllary problem (to solve problems with no apparent basis, i.e. no apparent identity basic matrix fromed in matrix A) is then: \
$  \text{min } e\cdot y$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$
\
\
Hence our problem for the auxillary problem can be proven to be the following: \
$\text{min } e\cdot(b-Ax)$ \
$  \text{s.t. } Ax + I_n y = b$ \
$  x \geq 0, y \geq 0$ \
$ e = (1,...,1)^T$ \
\
So our tableau becomes:
| $-e\cdot b$| $-eA$ | $0...0$ |
| :----------:| :-----:| :----: |
| $b$        |   $A$  | $I$ |

Notice the following facts:
1. Our tableau can be represented as a matrix of size $(m+1) \times (m+n+1)$
2. This tableau can be constructed numerically

We use numpy.linalg to compute matrix multiplication as prescribed above. \
Note that we only have a valid solution if the y variables are all 0, otherwise the original problem's constraints are violated.

### Tableau construction tests

In [12]:
from two_phase_simplex import TwoPhaseSimplex

# test the basic tableau construction of the auxillary problem
# simple 2x2 matrix case
A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
x.solve_phase_one()
print(x.get_tableau())

# non-square matrix
A = [[3,2,2],[4,5,4],[2,1,1],[0,1,1]]
b = [1,2,3,4]
c = [-1,-2,3]
y = TwoPhaseSimplex(A,b,c)
y.solve_phase_one()
print(y.get_tableau())

# check if these two outputs check out

[[ 0.  0.  0.  1.  1.]
 [ 2.  1.  0.  1.  0.]
 [ 1.  0.  1. -1.  1.]]
[[-6.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  3.50000000e+00  0.00000000e+00  1.00000000e+00
   2.50000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.00000000e+00  0.00000000e+00
  -2.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.50000000e+00  5.00000000e-01  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 3.50000000e+00 -1.50000000e+00  0.00000000e+00  0.00000000e+00
  -5.00000000e-01  5.55111512e-17  0.00000000e+00  1.00000000e+00]]


### Tableau feasibility tests

#### Feasiblity via violation of auxillary problems non-negativity constaint

In [13]:
# Simple problem (can be solved using normal gaussian elimination lol)

A = [[1,0],[1,1]]
b = [2,3]
c = [1,1]
x = TwoPhaseSimplex(A,b,c)
if (x.solve_program()):
    print(x.get_solution())

# unbounded problem

A = [[3,4,5],[42,5,1],[2,5,4]]
b = [1,2,3]
c = [2,3,1]

y = TwoPhaseSimplex(A,b,c)
if y.solve_program():
    print(y.get_solution())

# higher dimension bounded problem

A = [[2,3,1,0],[3,1,0,-1]]
b = [6,3]
c = [-4,-5,0,0]

z = TwoPhaseSimplex(A,b,c)
if z.solve_program():
    print(z.get_solution())

{'x1': 2.0, 'x2': 1.0}
{'x1': 3.0, 'x2': 0.0, 'x3': 0.0, 'x4': 6.0}


## Random Test Cases

In [14]:
# produce random test cases

test_cases : dict = {"A" : [], "b" : [], "c" : []}

cases : int = 100

for i in range(cases):
    m : int = random.randint(2, 100)
    n : int = random.randint(2, 100)
    test_cases["A"].append(np.random.rand(m,n))
    test_cases["b"].append(np.random.rand(m))
    test_cases["c"].append(np.random.rand(n))

for i in range(cases):
    x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
    if x.solve_program():
        print(x.get_solution())

{'x1': 0.0, 'x2': 0.0, 'x3': 0.0, 'x4': 0.0, 'x5': 0.0, 'x6': 0.0, 'x7': 0.0, 'x8': 0.08070755258476527, 'x9': 0.0, 'x10': 0.0, 'x11': 0.0, 'x12': 0.0, 'x13': 0.0, 'x14': 0.0, 'x15': 0.0, 'x16': 0.0, 'x17': 0.0, 'x18': 0.0, 'x19': 0.0, 'x20': 0.0, 'x21': 0.0, 'x22': 0.0, 'x23': 0.0, 'x24': 0.0, 'x25': 0.0, 'x26': 0.0, 'x27': 0.0, 'x28': 0.6231258565517483, 'x29': 0.0, 'x30': 0.0, 'x31': 0.0, 'x32': 0.0, 'x33': 0.6780015805371454, 'x34': 0.0, 'x35': 0.0, 'x36': 0.0, 'x37': 0.0, 'x38': 0.0, 'x39': 0.0, 'x40': 0.0, 'x41': 0.0, 'x42': 0.0, 'x43': 0.0, 'x44': 0.0, 'x45': 0.0, 'x46': 0.0, 'x47': 0.0, 'x48': 0.0, 'x49': 0.0, 'x50': 0.0, 'x51': 0.0, 'x52': 0.0, 'x53': 0.0, 'x54': 0.0, 'x55': 0.0, 'x56': 0.0, 'x57': 0.0, 'x58': 0.0, 'x59': 0.0, 'x60': 0.0, 'x61': 0.0, 'x62': 0.0, 'x63': 0.0, 'x64': 0.0, 'x65': 0.0, 'x66': 0.0, 'x67': 0.0, 'x68': 0.0, 'x69': 0.0, 'x70': 0.0, 'x71': 0.0, 'x72': 0.0, 'x73': 0.0, 'x74': 0.0, 'x75': 0.0, 'x76': 0.0, 'x77': 0.0, 'x78': 0.0, 'x79': 0.0, 'x80': 0.0, 'x

### Observations from the random tests
A very large amount of 'random' (generated by numpy) problems are infeasible or unbounded, hence do not have an optimal solution. In the next couple cells I will try to present these facts using graphs.

In [15]:
def get_random_results(n : int) -> list:
    """
    Runs the two phase simplex solver using random shape of matrices and entries.
    Returns a list of n results.
    """
    for i in range(cases):
        m : int = random.randint(9, 300)
        n : int = m - 5
        test_cases["A"].append(np.random.rand(m,n))
        test_cases["b"].append(np.random.rand(m))
        test_cases["c"].append(np.random.rand(n))

    number_of_feasible_solns = 0

    for i in range(cases):
        x = TwoPhaseSimplex(test_cases["A"][i], test_cases["b"][i], test_cases["c"][i])
        if x.solve_program():
            number_of_feasible_solns+=1

    return number_of_feasible_solns

In [16]:
import matplotlib.pyplot as plt

n = 1000000

number_of_feasible_solns = get_random_results(n)

proportion_of_feasible_solns = number_of_feasible_solns/n

print(number_of_feasible_solns)
print(proportion_of_feasible_solns)

4
4e-06
